#!/bin/bash

amixer set Capture toggle && amixer get Capture | grep '\[off\]' && notify-send "You don't want to talk?" "Let me turn the mic OFF" || notify-send "Do you want to talk?" "The mic is ON now"
