modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["DEV", "WWW", "ENT", "VMS"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
disable_current_tag_swap = false

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "emacsclient -c -a 'emacs' --eval '(+vterm/here nil)'"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "firefox"
modifier = ["modkey"]
key = "i"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

# [[keybind]]
# command = "MoveWindowTop"
# modifier = ["modkey"]
# key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "a"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "a"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "s"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "d"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"
