#!/bin/sh

#LAUNCHERS
$HOME/.config/autostart.sh

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         3
bspc config window_gap           8
bspc config top_padding          40
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#FFFFFF"
bspc config presel_feedback_color "#FFFFFF"

#Single monitor
bspc monitor -d 1 2 3 4 5

bspc rule -a Emacs state=tiled

#bspc rule -a '*:Scratchpad' sticky=on state=floating hidden=on
